on:
  push:
    branches:
      - main
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
      REGION: us-west-1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: build
      run: sam build --use-container 

    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name knightsandgoblins-${BRANCH} --s3-bucket knightsandgoblins-${BRANCH} --capabilities CAPABILITY_IAM --region us-west-1 --parameter-overrides "BRANCH=${BRANCH}"